# handlers/states.py
SELECTING_REGION    = 0
SELECTING_PLAN      = 1
DEPOSITING          = 2
ENTERING_AMOUNT     = 3
CHOOSING_COIN       = 4
CONFIRMING_ORDER    = 5
WAITING_FOR_PAYMENT = 6
INTERCEPTING=7

# 👑 ADMIN FULFILLMENT STATES
ADMIN_SMDP       = 8
ADMIN_ACTIVATION = 9
ADMIN_QR         = 10
ADMIN_CONFIRM    = 11